# Generated by Django 4.2.1 on 2023-06-19 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_blog_pdf_file_alter_blog_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pdfs')),
            ],
        ),
        migrations.RemoveField(
            model_name='blog',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='blog',
            name='pdf_files',
            field=models.ManyToManyField(blank=True, to='blog.pdffile'),
        ),
    ]
