# Generated by Django 4.2.1 on 2023-06-19 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_pdffile_remove_blog_pdf_file_blog_pdf_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='pdf_files',
        ),
        migrations.AddField(
            model_name='blog',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs'),
        ),
        migrations.DeleteModel(
            name='PDFFile',
        ),
    ]
