# Generated by Django 4.2.1 on 2023-06-19 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_blog_pdf_files_blog_pdf_file_delete_pdffile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
